### ISSUE TITLE
Errors on install

### ISSUE THREAD

**Issue by SdeGeata** [alltopafi/MMM-DateCounter#1]
Greetings;

   I am currently installing you module. It is throwing errors on 'NPM Install'.

`pi@magick-mirror:~/MagicMirror/modules/MMM-DateCounter $ npm install
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /home/pi/MagicMirror/node_modules/caniuse-lite
npm ERR! dest /home/pi/MagicMirror/node_modules/.caniuse-lite-6h1pL5No
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/home/pi/MagicMirror/node_modules/caniuse-lite' -> '/home/pi/MagicMirror/node_modules/.caniuse-lite-6h1pL5No'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2023-02-21T16_33_36_812Z-debug-0.log`

**Comment by alltopafi** [comment]
There were some invalid installation instructions added to this repo on mistake, you should not need to run npm install on the module (there is no package.json ) you should just need to clone this repo in the module folder and configure with the settings you want. If you run into any more issues let me know!

**Comment by SdeGeata** [comment]
Ok, thanks! It seems to be running ok so far, though i am trying to figure out how to put the long date all on one line.

**Comment by alltopafi** [comment]
Sorry for the delay I did not see your latest response you might have to tweak the css to get it on one line.
