### ISSUE TITLE
Line under header

### ISSUE THREAD

**Issue by Plainbroke** [alltopafi/MMM-DateCounter#4]
How do I remove or at minimum shorten the line under the Header?

**Comment by Plainbroke** [comment]
@alltopafi 
How can I remove or shorten the line under the header?

**Comment by alltopafi** [comment]
Sorry for the delay, I just pushed a change that adds a class to that hr so now in your CSS you can do something like.

```
.date_counter_hr {
  border: 10px solid green;
}
```

Note:  If you are using multiple instances of the module you would need to reference the parent ids to have specific formatting per instance.
