### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by KristjanESPERANTO** [alltopafi/MMM-DateCounter#5]
It would be nice if you would add a license file. MagicMirror and most other modules use the MIT license, here is an example: <https://github.com/MagicMirrorOrg/MagicMirror/blob/master/LICENSE.md> :slightly_smiling_face: 

By the way: Without a license your module can't be displayed with a screenshot on [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on.

**Comment by alltopafi** [comment]
@KristjanESPERANTO added and I love the listing tool!

**Comment by KristjanESPERANTO** [comment]
Thanks for the quick reaction! One change suggestion: In the copyright line should be your name :slightly_smiling_face: 

And thanks for the credits! The current/"old" list is a bit messy since there are more than 1100 modules. A list with filters and a search function was absolutely lacking.

**Comment by KristjanESPERANTO** [comment]
By the way: Thanks for this module! :smiley:

**Comment by alltopafi** [comment]
Double updated and couldn't agree more!! Thanks again!
